In [1]:
import pandas as pd

In [2]:
d=pd.read_csv("Salary_Data.csv")
d

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0


In [3]:
d.columns

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='object')

In [4]:
d.columns[d.isnull().any()]

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='object')

In [5]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Age                  6702 non-null   float64
 1   Gender               6702 non-null   object 
 2   Education Level      6701 non-null   object 
 3   Job Title            6702 non-null   object 
 4   Years of Experience  6701 non-null   float64
 5   Salary               6699 non-null   float64
dtypes: float64(3), object(3)
memory usage: 314.4+ KB


In [6]:
d=d.drop(["Education Level"],axis=1)
d

,Age,Gender,Job Title,Years of Experience,Salary
0,32.0,Male,Software Engineer,5.0,90000.0
1,28.0,Female,Data Analyst,3.0,65000.0
2,45.0,Male,Senior Manager,15.0,150000.0
3,36.0,Female,Sales Associate,7.0,60000.0
4,52.0,Male,Director,20.0,200000.0
...,...,...,...,...,...
6699,49.0,Female,Director of Marketing,20.0,200000.0
6700,32.0,Male,Sales Associate,3.0,50000.0
6701,30.0,Female,Financial Manager,4.0,55000.0
6702,46.0,Male,Marketing Manager,14.0,140000.0


In [7]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Age                  6702 non-null   float64
 1   Gender               6702 non-null   object 
 2   Job Title            6702 non-null   object 
 3   Years of Experience  6701 non-null   float64
 4   Salary               6699 non-null   float64
dtypes: float64(3), object(2)
memory usage: 262.0+ KB


In [8]:
d["Gender"].value_counts()

Gender
Male      3674
Female    3014
Other       14
Name: count, dtype: int64

In [9]:
d["Job Title"].value_counts()

Job Title
Software Engineer             518
Data Scientist                453
Software Engineer Manager     376
Data Analyst                  363
Senior Project Engineer       318
                             ... 
Account Manager                 1
Help Desk Analyst               1
Senior Training Specialist      1
Junior Web Designer             1
Supply Chain Analyst            1
Name: count, Length: 193, dtype: int64

In [10]:
d["Job Title"].values

array(['Software Engineer', 'Data Analyst', 'Senior Manager', ...,
       'Financial Manager', 'Marketing Manager', 'Sales Executive'],
      shape=(6704,), dtype=object)

In [11]:
# r=[]
# for i in d["Job Title"]:
#     r.append(i)
# print(r)

In [12]:
# d=set(r)
# d

In [13]:
e=pd.get_dummies(d["Gender"])
e

,Female,Male,Other
0,False,True,False
1,True,False,False
2,False,True,False
3,True,False,False
4,False,True,False
...,...,...,...
6699,True,False,False
6700,False,True,False
6701,True,False,False
6702,False,True,False


In [14]:
d=pd.concat([d,e],axis=1)
d

,Age,Gender,Job Title,Years of Experience,Salary,Female,Male,Other
0,32.0,Male,Software Engineer,5.0,90000.0,False,True,False
1,28.0,Female,Data Analyst,3.0,65000.0,True,False,False
2,45.0,Male,Senior Manager,15.0,150000.0,False,True,False
3,36.0,Female,Sales Associate,7.0,60000.0,True,False,False
4,52.0,Male,Director,20.0,200000.0,False,True,False
...,...,...,...,...,...,...,...,...
6699,49.0,Female,Director of Marketing,20.0,200000.0,True,False,False
6700,32.0,Male,Sales Associate,3.0,50000.0,False,True,False
6701,30.0,Female,Financial Manager,4.0,55000.0,True,False,False
6702,46.0,Male,Marketing Manager,14.0,140000.0,False,True,False


In [15]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Age                  6702 non-null   float64
 1   Gender               6702 non-null   object 
 2   Job Title            6702 non-null   object 
 3   Years of Experience  6701 non-null   float64
 4   Salary               6699 non-null   float64
 5   Female               6704 non-null   bool   
 6   Male                 6704 non-null   bool   
 7   Other                6704 non-null   bool   
dtypes: bool(3), float64(3), object(2)
memory usage: 281.6+ KB


In [16]:
d=d.drop(["Gender"],axis=1)
d

,Age,Job Title,Years of Experience,Salary,Female,Male,Other
0,32.0,Software Engineer,5.0,90000.0,False,True,False
1,28.0,Data Analyst,3.0,65000.0,True,False,False
2,45.0,Senior Manager,15.0,150000.0,False,True,False
3,36.0,Sales Associate,7.0,60000.0,True,False,False
4,52.0,Director,20.0,200000.0,False,True,False
...,...,...,...,...,...,...,...
6699,49.0,Director of Marketing,20.0,200000.0,True,False,False
6700,32.0,Sales Associate,3.0,50000.0,False,True,False
6701,30.0,Financial Manager,4.0,55000.0,True,False,False
6702,46.0,Marketing Manager,14.0,140000.0,False,True,False


In [17]:
d["Years of Experience"]=d["Years of Experience"].fillna(d["Years of Experience"].mean())
d

,Age,Job Title,Years of Experience,Salary,Female,Male,Other
0,32.0,Software Engineer,5.0,90000.0,False,True,False
1,28.0,Data Analyst,3.0,65000.0,True,False,False
2,45.0,Senior Manager,15.0,150000.0,False,True,False
3,36.0,Sales Associate,7.0,60000.0,True,False,False
4,52.0,Director,20.0,200000.0,False,True,False
...,...,...,...,...,...,...,...
6699,49.0,Director of Marketing,20.0,200000.0,True,False,False
6700,32.0,Sales Associate,3.0,50000.0,False,True,False
6701,30.0,Financial Manager,4.0,55000.0,True,False,False
6702,46.0,Marketing Manager,14.0,140000.0,False,True,False


In [18]:
d.columns[d.isna().any()]

Index(['Age', 'Job Title', 'Salary'], dtype='object')

In [19]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Age                  6702 non-null   float64
 1   Job Title            6702 non-null   object 
 2   Years of Experience  6704 non-null   float64
 3   Salary               6699 non-null   float64
 4   Female               6704 non-null   bool   
 5   Male                 6704 non-null   bool   
 6   Other                6704 non-null   bool   
dtypes: bool(3), float64(3), object(1)
memory usage: 229.3+ KB


In [20]:
d["Salary"]=d["Salary"].fillna(d["Salary"].mean())
d

,Age,Job Title,Years of Experience,Salary,Female,Male,Other
0,32.0,Software Engineer,5.0,90000.0,False,True,False
1,28.0,Data Analyst,3.0,65000.0,True,False,False
2,45.0,Senior Manager,15.0,150000.0,False,True,False
3,36.0,Sales Associate,7.0,60000.0,True,False,False
4,52.0,Director,20.0,200000.0,False,True,False
...,...,...,...,...,...,...,...
6699,49.0,Director of Marketing,20.0,200000.0,True,False,False
6700,32.0,Sales Associate,3.0,50000.0,False,True,False
6701,30.0,Financial Manager,4.0,55000.0,True,False,False
6702,46.0,Marketing Manager,14.0,140000.0,False,True,False


In [21]:
d.columns[d.isna().any()]

Index(['Age', 'Job Title'], dtype='object')

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x=d[["Years of Experience"]]
y=d["Salary"]

x_train,x_test,y_tarin,y_test = train_test_split(x,y,train_size=0.9,random_state=42)
x_train

,Years of Experience
1867,15.0
865,5.0
1760,1.0
2184,3.0
196,11.0
...,...
3772,12.0
5191,3.0
5226,3.0
5390,4.0


In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
lr = LinearRegression()
lr.fit(x_train,y_tarin)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](1,)",[7028.64]
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](1,)",['Years of Experience']
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,5.856e+04
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,1
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int,1


In [26]:
y_pred = lr.predict(x_test)
y_pred

array([192108.03567786, 114793.00035504,  79649.80248103,  72621.16290623,
        79649.80248103,  65592.52333143,  65592.52333143,  72621.16290623,
       142907.55865425, 100735.72120544,  93707.08163064, 121821.63992984,
       114793.00035504,  72621.16290623,  72621.16290623, 192108.03567786,
        79649.80248103, 135878.91907945, 156964.83780385, 114793.00035504,
       142907.55865425, 121821.63992984,  72621.16290623, 185079.39610306,
       107764.36078024,  72621.16290623, 100735.72120544,  65592.52333143,
        65592.52333143,  79649.80248103, 199136.67525266,  65592.52333143,
        65592.52333143, 121821.63992984,  65592.52333143, 171022.11695345,
        93707.08163064, 107764.36078024,  65592.52333143,  72621.16290623,
       121821.63992984, 248337.15227627, 142907.55865425, 149936.19822905,
        72621.16290623,  93707.08163064,  93707.08163064,  79649.80248103,
       142907.55865425,  86678.44205583,  79649.80248103,  65592.52333143,
       121821.63992984, 1

In [27]:
lr.coef_

array([7028.6395748])

In [28]:
lr.intercept_

np.float64(58563.8837566266)

In [29]:
from sklearn.metrics import r2_score

In [30]:
r2_score(y_test,y_pred)

0.6690959551629008

In [33]:
import numpy as np
a=np.array([4,7]).reshape(-1,1)
b=lr.predict(a)
b

C:\Users\gavas\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([ 86678.44205583, 107764.36078024])