In [2]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
b=[1,2,3,4,5]
print(b)
print(type(b))

[1, 2, 3, 4, 5]
<class 'list'>


In [8]:
b=np.array(b)
print(type(b))

<class 'numpy.ndarray'>


In [9]:
c=np.array([[4,5,6,8],[2,6,8,4]])
c

array([[4, 5, 6, 8],
       [2, 6, 8, 4]])

In [10]:
np.ndim(c)

2

In [14]:
c.shape

(2, 4)

In [16]:
b.shape

(5,)

In [17]:
c.size

8

In [18]:
c.dtype

dtype('int64')

In [19]:
f=np.arange(1,51)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])